# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lc < Formula
  desc "This tool can be used collect from AWS cloudwatch log groups"
  homepage "https://github.com/steffakasid/lc"
  version "0.23"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/lc/releases/download/v0.23/lc_0.23_darwin_amd64.tar.gz"
      sha256 "e9834778cb596f536722d5179e8689aaf4c3306cca0b8f817063e09dc1c39d44"

      def install
        bin.install "lc"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/lc/releases/download/v0.23/lc_0.23_darwin_arm64.tar.gz"
      sha256 "d474826783d5d7c00b66562b11c9d016a34b89023a8fc90fd42de708787aa014"

      def install
        bin.install "lc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/lc/releases/download/v0.23/lc_0.23_linux_amd64.tar.gz"
        sha256 "84556fe3470fcde484297a966210e9ba96cd23d07a5e92cad3c3afe3a06b7fb6"

        def install
          bin.install "lc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/lc/releases/download/v0.23/lc_0.23_linux_arm64.tar.gz"
        sha256 "091da33094d8c85c52dbe28dbc407f559222a286813cde8ea4c20ea9a1824060"

        def install
          bin.install "lc"
        end
      end
    end
  end
end
