# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lc < Formula
  desc "This tool can be used collect from AWS cloudwatch log groups"
  homepage "https://github.com/steffakasid/lc"
  version "0.25"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/lc/releases/download/v0.25/lc_0.25_darwin_amd64.tar.gz"
      sha256 "07d1dc84a9ebe457ba80ee509f0fb9b4a1e393f9cf68f6f6c60dab534d8c8a60"

      def install
        bin.install "lc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/lc/releases/download/v0.25/lc_0.25_darwin_arm64.tar.gz"
      sha256 "470fdee67677fddbbaed0e5a23939e2222e2a91f23e15c8dca958aa1b57aabf7"

      def install
        bin.install "lc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/lc/releases/download/v0.25/lc_0.25_linux_amd64.tar.gz"
        sha256 "1dfbf89728759f00b790081509400f593b8d43887d363d6d5845a545656b67b2"

        def install
          bin.install "lc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/lc/releases/download/v0.25/lc_0.25_linux_arm64.tar.gz"
        sha256 "849544032a0658a9ff3676893a500674e29ab791b9fd633c8fb0dd13b8cd892d"

        def install
          bin.install "lc"
        end
      end
    end
  end
end
